@OneReactApp.Server_HostAddress = http://localhost:5031

GET {{OneReactApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{OneReactApp.Server_HostAddress}}/homeprop/
Accept:application/json